version: '3'

services:

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./schema.sql:/schema.sql
      - ./data.sql:/data.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jrtid
      POSTGRES_DB: jrtid
      POSTGRES_PASSWORD: 123456
    ports:
      - "45432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  es_data:
  grafana_data:
  influx_data:
  rabbitmq_data:
  rabbitmq_logs:

